### ISSUE TITLE
无法使用，提示

### ISSUE THREAD

**Issue by MikasaEureka** [yaoysyao/Auto_checkin_release#1]
The localize method is no longer necessary, as this time zone supports the fold attribute

**Comment by yaoysyao** [comment]
> The localize method is no longer necessary, as this time zone supports the fold attribute

警告还是错误？如果出现的是：apscheduler\util.py:428: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). 则不影响使用，是否方便提供完整的错误日志，就在checkin_log目录下

**Comment by MikasaEureka** [comment]
[AutoCheckIn][INFO][AutoCheckIn.py][161 line] message:The timing config is: day_of_week=>0-6,hour=>8,minute=>0
。。。是需要默认配置下时间吗

**Comment by MikasaEureka** [comment]
apscheduler\util.py:428: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html

**Comment by MikasaEureka** [comment]
没反应，正常来说会有输出信息吧

**Comment by yaoysyao** [comment]
> 没反应，正常来说会有输出信息吧

这个不算是错误，因为使用的是定时任务，不是启动exe就立即执行签到的，并且如果你不配置执行时间的话，默认就是每天早上八点开始执行签到，签到完成后会根据设置的is_print这个参数决定是否在控制台输出签到信息，下次更新会新增可以配置启动后立即执行一次签到而不是每天定时执行，那样的话就可以选择每日定时执行或者启动exe执行一次

**Comment by MikasaEureka** [comment]
emmm，现在还有几个问题：
1. 定时任务，是需要PC24h在线吗
2. 189的签到任务之前更新了，需要一个sessionkey，这个该怎么弄

**Comment by yaoysyao** [comment]
> emmm，现在还有几个问题：
> 
> 1. 定时任务，是需要PC24h在线吗
> 2. 189的签到任务之前更新了，需要一个sessionkey，这个该怎么弄

第一个问题：目前是以定时任务的方式执行，所以需要24h开机，因为最初我是以具有服务器为背景写的代码，下个版本计划推出直接注册为Windows服务，如果是服务器，可以通过配置文件配置定时任务，每天定时执行，如果是个人电脑，可以通过配置文件设置开机后服务自动启动执行一次签到
第二个问题：我的189签到过程是通过账户密码进行签到，首先需要进行登录然后签到，至于你说的sessionkey，我还没具体的了解过，需要分析下签到的请求才清楚

**Comment by MikasaEureka** [comment]
> 

1：如果是那种即用即消的模式也可以hhh
2：现在189的逻辑改啦，大佬你确定你的登录和签到没问题吗

**Comment by yaoysyao** [comment]
> > 
> 
> 1：如果是那种即用即消的模式也可以hhh 2：现在189的逻辑改啦，大佬你确定你的登录和签到没问题吗

1. 下个版本推出可以打开直接签到的模式，这几天正在测试做成Windows服务的形式
2. 189的签到截止到今天，我的还可以用，之前不能用了，我修改了签到的逻辑

**Comment by MikasaEureka** [comment]
大佬，签到部分可以发一个参考代码吗

**Comment by yaoysyao** [comment]
> 大佬，签到部分可以发一个参考代码吗

GitHub上挺多的，可以找找看

**Comment by MikasaEureka** [comment]
找到啦，谢谢大佬
