### ISSUE TITLE
吾爱破解无法签到

### ISSUE THREAD

**Issue by witcherzard** [yaoysyao/Auto_checkin_release#10]
现在版本为Version: 0.1.14，之前旧版本的是可以签到的。
自从升级后，已经是按照指引cookies复制粘贴一个新的。一样无法签到了。
提示这个错误

开始执行任务 wuaipojie ....
wuaipojie 签到完毕, 签到信息:main function: wuaipojie checkin error, the error is 'NoneType' object has no attribute 'find'

**Comment by yaoysyao** [comment]
> 现在版本为Version: 0.1.14，之前旧版本的是可以签到的。 自从升级后，已经是按照指引cookies复制粘贴一个新的。一样无法签到了。 提示这个错误
> 
> 开始执行任务 wuaipojie .... wuaipojie 签到完毕, 签到信息:main function: wuaipojie checkin error, the error is 'NoneType' object has no attribute 'find'

正在查看问题

**Comment by yaoysyao** [comment]
> 现在版本为Version: 0.1.14，之前旧版本的是可以签到的。 自从升级后，已经是按照指引cookies复制粘贴一个新的。一样无法签到了。 提示这个错误
> 
> 开始执行任务 wuaipojie .... wuaipojie 签到完毕, 签到信息:main function: wuaipojie checkin error, the error is 'NoneType' object has no attribute 'find'

官方对于签到做了限制，脚本已失效

**Comment by witcherzard** [comment]
> > 现在版本为Version: 0.1.14，之前旧版本的是可以签到的。 自从升级后，已经是按照指引cookies复制粘贴一个新的。一样无法签到了。 提示这个错误
> > 开始执行任务 wuaipojie .... wuaipojie 签到完毕, 签到信息:main function: wuaipojie checkin error, the error is 'NoneType' object has no attribute 'find'
> 
> 官方对于签到做了限制，脚本已失效

其他docker的签到脚本对吾爱破解也失效了，暂时没有办法了
