### ISSUE TITLE
增加Telegram或企业微信通知

### ISSUE THREAD

**Issue by hn-kitty** [yaoysyao/Auto_checkin_release#13]
请问有计划增加Telegram或企业微信通知的计划吗

**Comment by yaoysyao** [comment]
> 请问有计划增加Telegram或企业微信通知的计划吗

暂无，目前在准备秋招，暂时没时间搞，只能有时间了修复BUG，或者增加一些简单的功能

**Comment by hn-kitty** [comment]
好的，感谢回复
