### ISSUE TITLE
有青龙拉库命令吗

### ISSUE THREAD

**Issue by wzgrx** [yaoysyao/Auto_checkin_release#15]
ql repo https://github.com/wd210010/only_for_happly.git "" "backup" "" ""
类似这种的，非常感谢·

**Comment by yaoysyao** [comment]
> ql repo https://github.com/wd210010/only_for_happly.git "" "backup" "" "" 类似这种的，非常感谢·

暂时没，只能通过PIP方式安装

**Comment by wzgrx** [comment]
> > ql repo https://github.com/wd210010/only_for_happly.git "" "backup" "" "" 类似这种的，非常感谢·
> 
> 暂时没，只能通过PIP方式安装

好的，谢谢
