### ISSUE TITLE
运行exe报错

### ISSUE THREAD

**Issue by sunmaojing** [yaoysyao/Auto_checkin_release#2]
apscheduler\util.py:428: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html

**Comment by yaoysyao** [comment]
> apscheduler\util.py:428: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html

这个不算错误，只是个警告，不影响使用，如果不想看到这个，可以使用最新版的，新增了其他平台签到，可以设置为Windows服务，支持立即执行签到和定时签到

**Comment by shuaiqidegaga** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/autodailycheckin", line 5, in <module>
    from yaoys_checkin.AutoCheckIn import main
ModuleNotFoundError: No module named 'yaoys_checkin.AutoCheckIn'
青龙运行出现这个问题
