### ISSUE TITLE
科研通able_sci签到不了，请问是什么问题

### ISSUE THREAD

**Issue by Li-Yaoting** [yaoysyao/Auto_checkin_release#3]
able_sci checkin complete, checkin message:main function: able_sci checkin error, the error is 'signpoint'

**Comment by yaoysyao** [comment]
可能是签到返回的字段的问题，建议更新到最新版，或者更新下cookie看看还会不会报错

**Comment by yaoysyao** [comment]
> able_sci checkin complete, checkin message:main function: able_sci checkin error, the error is 'signpoint'

兄弟，还有问题吗，没问题我关掉了
