### ISSUE TITLE
青龙怎么添加

### ISSUE THREAD

**Issue by WarlockFish** [yaoysyao/Auto_checkin_release#4]
请问青龙面板上怎么添加，yaoys-checkin包不存在，下载了autocheckin包，但是无法添加定时任务

**Comment by yaoysyao** [comment]
> 请问青龙面板上怎么添加，yaoys-checkin包不存在，下载了autocheckin包，但是无法添加定时任务

pip install yaoys_checkin

**Comment by yaoysyao** [comment]
> 请问青龙面板上怎么添加，yaoys-checkin包不存在，下载了autocheckin包，但是无法添加定时任务

我试了一下，好像可以安装，青龙试试pip install yaoys_checkin,实在不行后续我改个其他的名字，你下载了安装包还是exe?如果在本地运行的话，修改配置文件可以设置定时任务的执行时间

**Comment by yaoysyao** [comment]
> 请问青龙面板上怎么添加，yaoys-checkin包不存在，下载了autocheckin包，但是无法添加定时任务

已更新了最新版本，查看  青龙面板配置使用.md 在青龙面板进行安装

**Comment by WarlockFish** [comment]
yaoys-checkin 无法安装是因为青龙面板默认使用了douban源，将pip源换成pypi.tuna.tsinghua.edu.cn 即可

**Comment by yaoysyao** [comment]
> yaoys-checkin 无法安装是因为青龙面板默认使用了douban源，将pip源换成pypi.tuna.tsinghua.edu.cn 即可
 建议使用最新的安装，以后版本更新会使用最新的库
