### ISSUE TITLE
青龙面板还是搭建不了

### ISSUE THREAD

**Issue by bzxying** [yaoysyao/Auto_checkin_release#5]
找不到那个依赖文件，无法下载

**Comment by yaoysyao** [comment]
> 找不到那个依赖文件，无法下载

具体报错信息贴一下

**Comment by bzxying** [comment]
> > 找不到那个依赖文件，无法下载
> 
> 具体报错信息贴一下
开始安装依赖 autodailycheckin，开始时间 2023-08-04 10:27:25

Looking in indexes: https://pypi.doubanio.com/simple/
ERROR: Could not find a version that satisfies the requirement autodailycheckin (from versions: none)
ERROR: No matching distribution found for autodailycheckin

依赖安装失败，结束时间 2023-08-04 10:27:31，耗时 6 秒

**Comment by yaoysyao** [comment]
> > > 找不到那个依赖文件，无法下载
> > 
> > 
> > 具体报错信息贴一下
> > 开始安装依赖 autodailycheckin，开始时间 2023-08-04 10:27:25
> 
> Looking in indexes: https://pypi.doubanio.com/simple/ ERROR: Could not find a version that satisfies the requirement autodailycheckin (from versions: none) ERROR: No matching distribution found for autodailycheckin
> 
> 依赖安装失败，结束时间 2023-08-04 10:27:31，耗时 6 秒

换一个pip源，换成清华的，豆瓣这个不行

**Comment by bzxying** [comment]
又来了个新的问题
## 开始执行... 2023-08-06 18:33:00


##################################start auto checkin2023-08-06 18:33:05##################################
start checkin able_sci ....
able_sci checkin complete, checkin message:main function: able_sci checkin error, the error is list index out of range    

start checkin bilibili_live ....
bilibili_live checkin complete, checkin message:main function: bilibili_live checkin error, the error is 'latin-1' codec can't encode characters in position 0-9: ordinal not in range(256)    

start checkin bilibili_icon ....
bilibili_icon checkin complete, checkin message:main function: bilibili checkin error, the error is 'latin-1' codec can't encode characters in position 0-9: ordinal not in range(256)    

start checkin cloud189 ....
cloud189 checkin complete, checkin message:main function: cloud189 checkin error, the error is 'toUrl'    

start checkin glados ....
glados checkin complete, checkin message:main function: gloads checkin error, the error is list index out of range    

start checkin gu_fen_xue_shu ....
gu_fen_xue_shu checkin complete, checkin message:main function: gufenxueshu checkin error, the error is 'latin-1' codec can't encode characters in position 0-9: ordinal not in range(256)    

start checkin aliyunpan ....
aliyunpan checkin complete, checkin message:[aliyun_Account_1]:RefreshToken已失效，请更新RefreshToken，获取 access token 失败, 错误信息: {'code': 'InvalidParameter.RefreshToken', 'message': 'The input parameter refresh_token is not valid. ', 'requestId': None}

start checkin wps_vip ....
wps_vip checkin complete, checkin message:[Wps_vip_Account_1] :签到信息: 获取会员时长失败，由于Wps签到策略，请手动签到获取会员时长	    

start checkin wps_cloud ....
wps_cloud checkin complete, checkin message:[Wps_cloud_Account_1] :签到信息: 签到失败，请手动签到	    

start checkin tieba ....
tieba checkin complete, checkin message:main function: tieba checkin error, the error is list index out of range    

start checkin wuaipojie ....
wuaipojie checkin complete, checkin message:[wuaipojie_Account_1] cookie中未包含htVC_2132_saltkey或htVC_2132_auth字段，请检查cookie
start checkin jiaoyimao ....
jiaoyimao checkin complete, checkin message:main function: jiaoyimao checkin error, the error is list index out of range    

start checkin piaoyunge ....
piaoyunge checkin complete, checkin message:main function: 飘云阁配置文件错误，错误信息：list index out of range    

 push message to pushPlus ....
push message to pushPlus complete
 push message to server ....
push message to server complete


## 执行结束... 2023-08-06 18:36:15  耗时 195 秒

**Comment by yaoysyao** [comment]
> 又来了个新的问题
> 
> ## 开始执行... 2023-08-06 18:33:00
> ##################################start auto checkin2023-08-06 18:33:05################################## start checkin able_sci .... able_sci checkin complete, checkin message:main function: able_sci checkin error, the error is list index out of range
> 
> start checkin bilibili_live .... bilibili_live checkin complete, checkin message:main function: bilibili_live checkin error, the error is 'latin-1' codec can't encode characters in position 0-9: ordinal not in range(256)
> 
> start checkin bilibili_icon .... bilibili_icon checkin complete, checkin message:main function: bilibili checkin error, the error is 'latin-1' codec can't encode characters in position 0-9: ordinal not in range(256)
> 
> start checkin cloud189 .... cloud189 checkin complete, checkin message:main function: cloud189 checkin error, the error is 'toUrl'
> 
> start checkin glados .... glados checkin complete, checkin message:main function: gloads checkin error, the error is list index out of range
> 
> start checkin gu_fen_xue_shu .... gu_fen_xue_shu checkin complete, checkin message:main function: gufenxueshu checkin error, the error is 'latin-1' codec can't encode characters in position 0-9: ordinal not in range(256)
> 
> start checkin aliyunpan .... aliyunpan checkin complete, checkin message:[aliyun_Account_1]:RefreshToken已失效，请更新RefreshToken，获取 access token 失败, 错误信息: {'code': 'InvalidParameter.RefreshToken', 'message': 'The input parameter refresh_token is not valid. ', 'requestId': None}
> 
> start checkin wps_vip .... wps_vip checkin complete, checkin message:[Wps_vip_Account_1] :签到信息: 获取会员时长失败，由于Wps签到策略，请手动签到获取会员时长
> 
> start checkin wps_cloud .... wps_cloud checkin complete, checkin message:[Wps_cloud_Account_1] :签到信息: 签到失败，请手动签到
> 
> start checkin tieba .... tieba checkin complete, checkin message:main function: tieba checkin error, the error is list index out of range
> 
> start checkin wuaipojie .... wuaipojie checkin complete, checkin message:[wuaipojie_Account_1] cookie中未包含htVC_2132_saltkey或htVC_2132_auth字段，请检查cookie start checkin jiaoyimao .... jiaoyimao checkin complete, checkin message:main function: jiaoyimao checkin error, the error is list index out of range
> 
> start checkin piaoyunge .... piaoyunge checkin complete, checkin message:main function: 飘云阁配置文件错误，错误信息：list index out of range
> 
> push message to pushPlus .... push message to pushPlus complete push message to server .... push message to server complete
> 
> ## 执行结束... 2023-08-06 18:36:15 耗时 195 秒

你的配置文件是不是有问题，可以前往https://www.json.cn/  验证下是不是标准的JSON格式

**Comment by bzxying** [comment]
格式没有错啊
## 开始执行... 2023-08-08 09:47:27


##################################start auto checkin2023-08-08 09:47:33##################################
start checkin wps_vip ....
wps_vip checkin complete, checkin message:[Wps_vip_Account_1] :签到信息: 获取会员时长异常	    

start checkin wps_cloud ....
wps_cloud checkin complete, checkin message:[Wps_cloud_Account_1] :签到信息: 签到成功，已成功获取云空间	    

 push message to pushPlus ....
push message to pushPlus complete
 push message to server ....
push message to server complete


## 执行结束... 2023-08-08 09:49:41  耗时 134 秒　　
会员时常无法获取，可以获取云空间

**Comment by bzxying** [comment]
> 格式没有错啊
> 
> ## 开始执行... 2023-08-08 09:47:27
> ##################################start auto checkin2023-08-08 09:47:33################################## start checkin wps_vip .... wps_vip checkin complete, checkin message:[Wps_vip_Account_1] :签到信息: 获取会员时长异常
> 
> start checkin wps_cloud .... wps_cloud checkin complete, checkin message:[Wps_cloud_Account_1] :签到信息: 签到成功，已成功获取云空间
> 
> push message to pushPlus .... push message to pushPlus complete push message to server .... push message to server complete
> 
> ## 执行结束... 2023-08-08 09:49:41 耗时 134 秒　　
> 会员时常无法获取，可以获取云空间

那个任务好像只能手动获取会员时长

**Comment by yaoysyao** [comment]
> > 格式没有错啊
> > ## 开始执行... 2023-08-08 09:47:27
> > ##################################start auto checkin2023-08-08 09:47:33################################## start checkin wps_vip .... wps_vip checkin complete, checkin message:[Wps_vip_Account_1] :签到信息: 获取会员时长异常
> > start checkin wps_cloud .... wps_cloud checkin complete, checkin message:[Wps_cloud_Account_1] :签到信息: 签到成功，已成功获取云空间
> > push message to pushPlus .... push message to pushPlus complete push message to server .... push message to server complete
> > ## 执行结束... 2023-08-08 09:49:41 耗时 134 秒　　
> > 会员时常无法获取，可以获取云空间
> 
> 那个任务好像只能手动获取会员时长

WPSW获取会员挂了，现在WPS获取会员需要传加密的参数，没解析出来这个，下个版本就取消获取WPS会员了，云空间的话好像每周需要一次手动获取，要不然会有验证码，验证码没办法绕过
