### ISSUE TITLE
怎么指定只执行天翼云盘签到任务-群晖docker青龙面板天翼云盘签到可以正常使用23年8月6号

### ISSUE THREAD

**Issue by kukuos** [yaoysyao/Auto_checkin_release#6]
我安装教程使用的task autodailycheckin发现运行时间要三分钟，我想让任务只执行天翼云盘/或者使用多个任务/除该任务以外全部执行该使用什么命令

**Comment by yaoysyao** [comment]
配置文件里面有参数可以设置，
"cloud189": {
      "is_checkin": true,
      "push_message": true,
      "checkin_verification": {
        "phone": "单账号配置，不需要写在json数组中，多账号参考上面",
        "password": "单账号配置，不需要写在json数组中，多账号参考上面"
      }
    }
is_checkin参数是指定是否执行签到，其他的也一样，想要签到的设置为true,不想签到的设置为false
另外执行时间过长是由于我设置了多账号之间签到时需要休眠一定时间，防止账号出问题，后续我打算把这个配置写在配置文件里，可以自己设置多账号签到休眠时长

**Comment by kukuos** [comment]
非常感谢
