### ISSUE TITLE
v0.1.11 开发计划

### ISSUE THREAD

**Issue by yaoysyao** [yaoysyao/Auto_checkin_release#7]
1. 由于目前多账号签到设置了休眠时间，还有贴吧多个吧之间签到也设置了休眠时间，导致签到时间太久了，后续将把休眠时间的配置写在配置文件里，可以自己自定义，设置休眠时间的主要目的是防止账号风控
2. 计划支持阿里云盘新版本签到任务，包括上传文件、照片、创建相册等，正在测试中
3. 使用多线程签到，减少见到所需时间

**Comment by AlvaTsou** [comment]
请问wpsvip签到时长这个是不是改了没效果了

**Comment by yaoysyao** [comment]
> 请问wpsvip签到时长这个是不是改了没效果了

这个功能不行了，WPS修改了签到策略，每次签到需要加密的参数，暂时没解析出来这个参数怎么来的
